fos_rest:
    body_converter:
        enabled: true
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
    serializer:
        serialize_null: true
    format_listener:
        rules:
            - { path: "^/", fallback_format: "json", priorities: ["json"] }
    param_fetcher_listener: force
